sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ""
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIOSS_ACCESS_KEY_ID}
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET}
    bucket-name: sky-mine
    #用的是我自己的
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: wx8bc8b83bea90e136
    secret: d7d1df7864a1b894a5af68427008773e

